/**:
  diff_drive_controller:
    ros__parameters:
    
      linear:
        x:
          has_velocity_limits: true
          max_velocity: 0.22
          min_velocity: -0.22
          has_acceleration_limits: true
          max_acceleration: 2.5

      angular:
        z:
          has_velocity_limits: true
          max_velocity: 2.84
          min_velocity: -2.84
          has_acceleration_limits: true
          max_acceleration: 3.2
